import { Box, Typography } from "@mui/material";
import { ReduxProvider } from "@redux";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useDispatch, useSelector } from "react-redux";
import { changeTheme } from "@redux";
import { themeSelector } from "@redux";
import { Button, IconButton } from "@mui/material";
import { useTheme } from "@mui/material/styles";
import { Card } from "@mui/material";
import Brightness4Icon from "@mui/icons-material/Brightness4";
import Brightness7Icon from "@mui/icons-material/Brightness7";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}

const InsideReduxProvider = ({ children }: { children: React.ReactNode }) => {
  //const theme = useSelector(themeSelector);
  //const dispatch = useDispatch();
  //const muiTheme = useTheme();
  return (
    <Box
      sx={{
        bgcolor: "background.default",
        minHeight: "100vh",
        color: "text.primary",
        display: "flex",
        flexDirection: "column",
      }}
    >
      <Box
        sx={{
          display: "flex",
          flexDirection: "row",
          justifyContent: "space-between",
        }}
      >
        <div></div>
        <Typography>Hey</Typography>
      </Box>
      {children}
    </Box>
  );
};
